# Generated by Django 5.2 on 2025-05-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
