# Generated by Django 5.2 on 2025-05-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
